name: Report a Bug
description: Something isn't working as expected?
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us identify and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Send request to...
        2. Use payload...
        3. Observe...
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The API should return...
    validations:
      required: false

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, the API returned...
    validations:
      required: false

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs / Stack Trace
      description: Paste any error logs or stack traces here.
      render: bash
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System down/unavailable)
        - High (Core functionality broken)
        - Medium (Feature not working)
        - Low (Minor issue)
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment.
      placeholder: |
        - Node.js version: 20.x
        - Database: MySQL 8.0
        - Redis: 7.x
        - OS: Linux
      validations:
        required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem?
      placeholder: Add any other context here...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked existing issues for duplicates
          required: false
        - label: I have provided clear reproduction steps
          required: false
        - label: I have included relevant error logs
          required: false
