name: Request a Feature
description: Suggest an idea for improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Your ideas help make BrowsePing better.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Describe the feature you'd like...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Problem Statement
      description: What problem does this solve? Why do you need it?
      placeholder: This would help because...
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: The feature should work by...
    validations:
      required: false

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Are there other ways to solve this problem?
      placeholder: Other approaches could include...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information?
      placeholder: Add screenshots, API examples, or other context...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked existing issues for similar requests
          required: false
        - label: This feature would be useful for multiple users
          required: false
        - label: I have provided use cases and examples
          required: false
