name: Security Vulnerability
description: Report a security issue (PRIVATE - use email for critical issues)
title: "[SECURITY] "
labels: ["security", "needs-triage"]
confidential: true
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: For critical security vulnerabilities, please report via email instead:
        - Email: [support@browseping.com](mailto:support@browseping.com?subject=SECURITY:)
        - Direct: [akashkumar.dev00@gmail.com](mailto:akashkumar.dev00@gmail.com?subject=URGENT%20SECURITY:)
        
        See [SECURITY.md](../SECURITY.md) for details.

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: There is a potential SQL injection vulnerability in...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Security Impact
      description: What is the potential impact of this vulnerability?
      placeholder: |
        An attacker could:
        - Access unauthorized user data
        - Modify database records
        - Execute arbitrary code
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Exploit
      description: How can this vulnerability be exploited?
      placeholder: |
        1. Send POST request to /api/v1/search
        2. Include payload: {"query": "' OR 1=1 --"}
        3. Observe unauthorized data returned
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical is this vulnerability?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the code/system are affected?
      placeholder: |
        - File: src/routes/search.ts
        - Function: searchFriends()
        - Endpoint: POST /api/friends/search
    validations:
      required: false

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: Do you have a suggested fix or mitigation?
      placeholder: |
        Use parameterized queries:
        const result = await db.query(
          'SELECT * FROM users WHERE name = ?',
          [searchTerm]
        );
    validations:
      required: false

  - type: textarea
    id: contact
    attributes:
      label: Your Contact Information
      description: How can we contact you for follow-up?
      placeholder: |
        Email: your.email@example.com
        GitHub: @yourusername
        Preferred contact method: Email
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have not disclosed this vulnerability publicly
          required: true
        - label: I have not opened this as a regular public issue
          required: false
        - label: I am willing to work with maintainers on a fix
          required: false
